### ISSUE TITLE
Startup - While mounting NFS it hangs

### ISSUE THREAD

**Issue by bitliner** [geerlingguy/packer-ubuntu-1604#14] opened 2016-11-07 10:28 UTC
It might be the same of https://github.com/geerlingguy/drupal-vm/issues/245

When I start the machine `vagrant up`, with NFS, it hangs while mounting NFS.

My host is **MaxOS Sierra**.

The settings in Vagrantfile are:

```
config.vm.network :private_network, ip: '192.168.50.50'
config.vm.synced_folder '.', '/vagrant', nfs: true, mount_options: ['vers=3'], nfs_udp: false, nfs_version: 3
```

If I run `vagrant up --debug`, I can see that it gets stuck on:

```
DEBUG ssh: Sending SSH keep-alive...
```

It tries again and again, but apparently SSH does not connect.

Without NFS everything works fine.

On my host, the output of `lsof |egrep nfs` is:

```
nfsd      33485           root    5u  IPv4 0x6d5874c158f8f163      0t0  UDP *:768
nfsd      33485           root    6u  IPv6 0x6d5874c158f919c3      0t0  UDP *:phonebook
nfsd      33485           root    7u  IPv4 0x6d5874c16b55c24b      0t0  TCP *:945 (LISTEN)
nfsd      33485           root    8u  IPv6 0x6d5874c1730df1e3      0t0  TCP *:944 (LISTEN)
nfsd      33485           root    9u  IPv4 0x6d5874c15af0905b      0t0  TCP *:nfsd (LISTEN)
nfsd      33485           root   10u  IPv6 0x6d5874c16cae81e3      0t0  TCP *:nfsd (LISTEN)
```

An error that it throws but not nfs related, is `mesg: ttyname failed: Inappropriate ioctl for device`. Could it be also that this error then causes the error while mounting NFS?

**Comment by geerlingguy** [comment] 2017-02-17 14:51
The ttyname error is unrelated, but I haven't seen this issue lately—what version of VirtualBox are you running? (Or VMware?).

**Comment by it-praktyk** [comment] 2017-05-24 19:56
I observed the same when I tested builded boxes - VMware 12.5.6 on Linux Fedora 25 - using Vagrantfile from the project.

Due that boxes (after my improvements) have correctly installed integration components I removed this option and /vagrant folder is synced using native (based on integration components) method. 

The related pull request #22

**Comment by it-praktyk** [comment] 2017-11-18 19:10
The issue is resolved in [the project maintained by me](https://github.com/it-praktyk/packer-ubuntu-1604).

**Comment by geerlingguy** [comment] 2018-05-18 19:13
Closing this as I have not seen this issue reported recently on any platforms running VirtualBox.

**Closed by geerlingguy** 2018-05-18 19:13 UTC
